#====================================
#
# ONLY SUPPORT .YML FILE NOT .YAML
#
#=====================================

Banners:
  - ExampleBanner.yml

Pools:
  - ExamplePool.yml

MySQL:
  Host: localhost
  Port: 3306
  User: root
  Password: CraftyCrates
  Database: CraftyCrates

