#====================================
#
# ONLY SUPPORT .YML FILE NOT .YAML
#
#=====================================

Banners:
  - ExampleBanner.yml

Pools:
  - ExamplePool.yml

MySQL:
  Host: localhost
  Port: 3306
  User: root
  Password: CraftyCrates
  Database: CraftyCrates
  DummyData:
    SendRate: 300
    Display: true

GUIs:
  Info:
    Title: "&dGacha Info: <display> &8| &2<banner>"
    Layout:
      - "BBBBBBBBB"
      - ""
      - ""
      - ""
      - ""
      - "PBBBIBBBN"
    Info-Slot: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 31, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]
    Next-Page-Slot: [53]
    Previous-Page-Slot: [45]
    #Avaiable placeholders:
    # <banner>, <uprate_pool>, <uprate_minimum>, <uprate_enable>, <uprate_additional>
    Items:
      B:
        Material: BLACK_STAINED_GLASS_PANE
        Amount: 1
        Display: "&f "
        Lore: []
        ModelData: 0
      N:
        Material: LIME_STAINED_GLASS_PANE
        Amount: 1
        Display: "&aNext Page"
        Lore: [ ]
        ModelData: 0
      P:
        Material: RED_STAINED_GLASS_PANE
        Amount: 1
        Display: "&cPrevious Page"
        Lore: [ ]
        ModelData: 0
      I:
        Material: NETHER_STAR
        Amount: 1
        Display: "&eGacha Info:"
        Lore:
          - "&fBanner: &b<banner>"
          - "&fChance of this pool: &b<pool_chance>"
          - "&fRate Increment at: &b<uprate_minimum>"
          - "&fUprate pool: &b<uprate_pool>"

  Logs:
    Title: "&dGacha Logs: <banner>"
    Layout:
      - ""
      - ""
      - ""
      - ""
      - ""
      - "PBBBIBBBN"
    Logs-Slot: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]
    Next-Page-Slot: [53]
    Previous-Page-Slot: [45]
    #Available placeholder:
    # <banner>, <uprate_pool>, <uprate_minimum>, <uprate_enable>, <uprate_additional>, <current_rate>, <current_rolls>, <total_rolls>
    Items:
      B:
        Material: BLACK_STAINED_GLASS_PANE
        Amount: 1
        Display: "&f "
        Lore: []
        ModelData: 0
      N:
        Material: LIME_STAINED_GLASS_PANE
        Amount: 1
        Display: "&aNext Page"
        Lore: [ ]
        ModelData: 0
      P:
        Material: RED_STAINED_GLASS_PANE
        Amount: 1
        Display: "&cPrevious Page"
        Lore: [ ]
        ModelData: 0
      I:
        Material: NETHER_STAR
        Amount: 1
        Display: "&eGacha Logs:"
        Lore:
          - "&fBanner: &b<banner>"
          - "&fTotal Pulls: &b<total_rolls>"
          - "&fCurrent Pulls: &b<current_rolls>"
          - "&f"

Languages:
  commands:
    open:
      invalid-argument: "&cInvalid Arguments! Please use /craftycrates open <bannerID> <amount>"
      unknown-id: "&cInvalid Banner ID, please check your arguments! (case sensitive)"
    info:
      invalid-argument: "&cInvalid Arguments! Please use /craftycrates info <bannerID"
      unknown-id: "&cInvalid Banner ID, please check your arguments! (case sensitive)"
    logs:
      invalid-argument: "&cInvalid Arguments! Please use /craftycrates logs <bannerID>"
      unknown-id: "&cInvalid Banner ID, please check your arguments! (case sensitive)"
    reload:
      reloading: "&6Reloading Configuration. . ."
      reloaded: "&aReloaded Configuration! &e(<time>ms)"
    help:
      - "&6CraftyCrates Help command:"
      - "   &6/cc open <BannerID> <amount> &f- Open the Gacha with specific amount"
      - "   &6/cc info <BannerID> &f- Get info of specific Banner"
      - "   &6/cc logs <BannerID> &f- Get Your logs of specific Banner"
      - "   &6/cc reload &f- Reload the configuration"
      - "   &6/cc help &f- Open this menu"
    no-permission: "&cSorry but you are not allowed to use this command!"

  pool-file:
    loading: "&eLoading Pool Files. . ."
    loaded: "&aLoaded Pool File: <file>"
    not-found: "&cUnable to load Pool File: <file> (File not found)"
    item-not-found: "&cCould not find MMOItem with Type: <type> and ID: <id>! Please check your configuration!"

  banner-file:
    loading: "&eLoading Banner Files . . ."
    loaded: "&aLoaded Banner File: <file>"
    pool-not-found: "&cUnable to load Banner File: <file> (Pool file not found)"
    not-found: "&cUnable to load Banner File: <file> (File not found)"
    invalid: "&cUnable to load Banner File: <file> (Invalid Rarities node)"

  MySQL:
    connecting: "&eConnecting to MySQL Server. . ."
    connected: "&aConnected to MySQL Server!"
    unable: "&cUnable to connect to MySQL Server. Please check your configuration, Disabling Plugin"
    dummy-data: "Sending Dummy Data to prevent MySQL Server Timed out!"
    check-table: "&dChecking MySQL Tables. . ."
    loaded: "&aSuccessfully Loaded MySQL Table: <table>"
    unable-load: "&cUnable to load MySQL Table: <table>"

  others:
    register-event-handler: "&eRegistering Plugin Event Handlers. . ."
    success-event-handler: "&aSuccessfully Registered all Event Handlers!"

